### ISSUE TITLE
Investigate adding type checks to the project

### ISSUE THREAD

**Issue by chrisalley** [pundit-community/pundit-matchers#80]
Despite some [views to the contrary](https://world.hey.com/dhh/programming-types-and-mindsets-5b8490bc), types can add extra safety and stability to a project, at the expense of some extra typing/more verbose code.

Since Ruby is a dynamically typed language, if Pundit Matchers was to add type signatures to the project, this would need to be added as a seperate dependency. Some options include:

---

## RBS

https://github.com/ruby/rbs

The official way of writing type signatures, a seperate gem but part of the Ruby project. Signatures are written in a seperate file and can be [tested](https://github.com/ruby/rbs/blob/master/docs/sigs.md#testing-signatures).

## Sorbet

https://sorbet.org

Another type checker from Stripe that predates RBS. Type signatures are written in the same file, above the method definition.

---

Whatever option is chosen would go through GitHub Actions.

**Comment by tagliala** [comment]
Recently RBS has been added to [money](https://github.com/RubyMoney/money), but I really don't like all the duplication (included duplicated docs) there 😞

**Comment by chrisalley** [comment]
I'm not planning to add type signatures myself, so I'm happy to close this issue if there's no interest.

**Comment by tagliala** [comment]
I would also close here, since this is also a non-production library
